### ISSUE TITLE
The new server cannot find the cluster config when doing snapshot.

### ISSUE THREAD

**Issue by nicelulu** [eBay/NuRaft#241] opened 2021-07-31 05:09 UTC
Hi, thank you. We encountered some problems with ```add_srv```. There are now 3 node servers, and it is set to take a snapshot every time 3000000 logs are added. This cluster has been running for a period of time to take a snapshot, and then re-elections were conducted several times, and a new cluster config was generated. Both the config log idx and the previous log idx are greater than 3000000. At this time, a new node is added and the log will be synchronized. When the synchronization reaches 3000000, a snapshot will be taken, but at this time, no cluster config smaller than ```committed_idx``` will be found.

**Comment by nicelulu** [comment] 2021-07-31 05:10
https://github.com/eBay/NuRaft/pull/242

**Comment by greensky00** [comment] 2021-08-01 17:26
Hi @nicelulu 
Thanks for bringing this issue.

I'd like to understand what exactly the issue is. Can you please elaborate more?
* If we face the above situation, what is the problem? (crash, system exit, ...)
* Your snapshot distance is `3000000`, what are the values of other parameters? especially `reserved_log_items_` and `log_sync_stop_gap_`.

**Comment by nicelulu** [comment] 2021-08-02 03:16
Thank you @greensky00.
```reserved_log_items_``` is 10000000
```snapshot_distance``` is 3000000
```log_sync_stop_gap_``` is 99999

At present, the entries in the log_store of the old three-node service are from 0 to 3700000, and the ```log_idx_``` of the current ```cluster_config``` is 3600100, and the ```prev_log_idx_``` is 3600000. After we add a new node, we will first get ```cluster_config``` from the leader, and then synchronize the log from 0. When the log reaches 3000000, the node will do ```snapshot_and_compact```. At this time, it will look for ```cluster_config``` smaller than the current ```committed_idx``` in log_store. Both ```log_idx_``` and ```prev_log_idx_``` of the current ```cluster_config``` of the node exceed the maximum log_idx in ```log_store_```.


https://github.com/eBay/NuRaft/blob/0ffb76b68a2d58174d3c7cd195747b69c2a87ef4/src/handle_commit.cxx#L465

**Comment by nicelulu** [comment] 2021-08-02 03:33
I have two other questions for advice. 

1. join_cluster_request will synchronize the current cluster_config to the new node. What is the effect of this?
2. What is the practical use of saving last_config_ in snapshot?

**Comment by greensky00** [comment] 2021-08-02 04:18
@nicelulu 
Since your `reserved_log_items_` is big enough, the new node should have all logs from 1 to 3000000, including all previous configs. If the current config's log index is bigger than `committed_idx`, it will do backward scanning through `prev_log_idx_` until it finds the first config whose index is equal to or smaller than `committed_idx`:
https://github.com/eBay/NuRaft/blob/0ffb76b68a2d58174d3c7cd195747b69c2a87ef4/src/handle_commit.cxx#L462-L467
Can you please investigate why your case couldn't find the config?

Regarding your questions:
1. At the time a new node joins the cluster, it should have the latest membership list, otherwise it may disrupt the cluster due to quorum difference.
2. Applying a snapshot of log index `X` should have the same effect (i.e., the same state machine data) of replaying logs from 1 to `X`, including the up-to-date config at the time `X` was committed.

**Comment by greensky00** [comment] 2021-08-02 04:30
Ok, I got your point. At the time the snapshot was created, `log_store_` didn't have the log of the index `conf->get_prev_log_idx()`.

**Comment by nicelulu** [comment] 2021-08-02 05:03
> 2\. Applying a snapshot of log index `X` should have the same effect (i.e., the same state machine data) of replaying logs from 1 to `X`, including the up-to-date config at the time `X` was committed.

@greensky00 Thank you for your answers.

So, in this case, ```log_store_``` didn't have the log of the index ```conf->get_prev_log_idx()```. Which one should be used for last_config_ in snapshot? Suppose the original cluster is "A B C" and the new node is D. When the new node D is doing ```snapshot_and_compact```, the conf obtained through ```ptr<cluster_config> conf = get_config();``` is "A B C". If you need to find a conf smaller than ```committed_idx```, it should only contain D.

**Comment by greensky00** [comment] 2021-08-02 05:48
@nicelulu 
The snapshot should have the old config, but that doesn't mean `D` will work with that old config -- it is still running on the latest config, and the old config is just a part of the snapshot. This is merely a snapshot creation process.

I just reviewed your PR. One concern is that `prev_configs_` is volatile. Once the new node D crashes and then restarts, it will still face the same problem. To avoid this, you should reconstruct `prev_configs_` during the initialization of Raft, but it will come with undesired costs as it requires the scanning of logs.

I'd rather do "skipping snapshot creation" under such a situation; it doesn't harm anything. We can add one more condition at the beginning of `snapshot_and_compact` as follows:
```c++
if (conf->get_log_idx() >= log_store_->next_slot()) {
    return;
}
```
so that any nodes who don't have the log for the latest config can skip the snapshot creation.

Please let me know if you want me to do it. Thanks.

**Comment by nicelulu** [comment] 2021-08-02 06:26
@greensky00 Thank you.
You are right.I will close the original PR and submit a new PR.As follows:
```
if ( conf->get_log_idx() >= log_store_->next_slot() && conf->get_prev_log_idx() >= log_store_->next_slot() ) {
    p_in("The latest config is not found, so skip the snapshot creation");
    return;
}
```

**Closed** 2021-08-02 18:17 UTC
